"""Add status to reviews

Revision ID: 8ac2dfe8e178
Revises: 5c575c76e092
Create Date: 2026-05-15 18:32:44.596698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac2dfe8e178'
down_revision = '5c575c76e092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_review_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
